// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/logger.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 日志类型
type Logger_Type int32

const (
	Logger_UNKNOWN Logger_Type = 0
	Logger_ZAP     Logger_Type = 1
	Logger_LOGRUS  Logger_Type = 2
	Logger_FLUENTD Logger_Type = 3
	Logger_ALIYUN  Logger_Type = 4
	Logger_TENCENT Logger_Type = 5
	Logger_ZEROLOG Logger_Type = 6
)

// Enum value maps for Logger_Type.
var (
	Logger_Type_name = map[int32]string{
		0: "UNKNOWN",
		1: "ZAP",
		2: "LOGRUS",
		3: "FLUENTD",
		4: "ALIYUN",
		5: "TENCENT",
		6: "ZEROLOG",
	}
	Logger_Type_value = map[string]int32{
		"UNKNOWN": 0,
		"ZAP":     1,
		"LOGRUS":  2,
		"FLUENTD": 3,
		"ALIYUN":  4,
		"TENCENT": 5,
		"ZEROLOG": 6,
	}
)

func (x Logger_Type) Enum() *Logger_Type {
	p := new(Logger_Type)
	*p = x
	return p
}

func (x Logger_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Logger_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_logger_proto_enumTypes[0].Descriptor()
}

func (Logger_Type) Type() protoreflect.EnumType {
	return &file_v1_logger_proto_enumTypes[0]
}

func (x Logger_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Logger_Type.Descriptor instead.
func (Logger_Type) EnumDescriptor() ([]byte, []int) {
	return file_v1_logger_proto_rawDescGZIP(), []int{0, 0}
}

// 日志
type Logger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Zap           *Logger_Zap            `protobuf:"bytes,2,opt,name=zap,proto3,oneof" json:"zap,omitempty"`
	Logrus        *Logger_Logrus         `protobuf:"bytes,3,opt,name=logrus,proto3,oneof" json:"logrus,omitempty"`
	Fluentd       *Logger_Flentd         `protobuf:"bytes,4,opt,name=fluentd,proto3,oneof" json:"fluentd,omitempty"`
	Aliyun        *Logger_Aliyun         `protobuf:"bytes,5,opt,name=aliyun,proto3,oneof" json:"aliyun,omitempty"`
	Tencent       *Logger_Tencent        `protobuf:"bytes,6,opt,name=tencent,proto3,oneof" json:"tencent,omitempty"`
	Zerolog       *Logger_Zerolog        `protobuf:"bytes,7,opt,name=zerolog,proto3,oneof" json:"zerolog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logger) Reset() {
	*x = Logger{}
	mi := &file_v1_logger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logger) ProtoMessage() {}

func (x *Logger) ProtoReflect() protoreflect.Message {
	mi := &file_v1_logger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logger.ProtoReflect.Descriptor instead.
func (*Logger) Descriptor() ([]byte, []int) {
	return file_v1_logger_proto_rawDescGZIP(), []int{0}
}

func (x *Logger) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Logger) GetZap() *Logger_Zap {
	if x != nil {
		return x.Zap
	}
	return nil
}

func (x *Logger) GetLogrus() *Logger_Logrus {
	if x != nil {
		return x.Logrus
	}
	return nil
}

func (x *Logger) GetFluentd() *Logger_Flentd {
	if x != nil {
		return x.Fluentd
	}
	return nil
}

func (x *Logger) GetAliyun() *Logger_Aliyun {
	if x != nil {
		return x.Aliyun
	}
	return nil
}

func (x *Logger) GetTencent() *Logger_Tencent {
	if x != nil {
		return x.Tencent
	}
	return nil
}

func (x *Logger) GetZerolog() *Logger_Zerolog {
	if x != nil {
		return x.Zerolog
	}
	return nil
}

// Zap
type Logger_Zap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogFilePath   string                 `protobuf:"bytes,1,opt,name=log_file_path,json=logFilePath,proto3" json:"log_file_path,omitempty"`     // 日志文件路径
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`                                      // 日志等级
	Caller        string                 `protobuf:"bytes,3,opt,name=caller,proto3" json:"caller,omitempty"`                                    // Caller显示格式(short, full, xkit), default: short
	LogToConsole  bool                   `protobuf:"varint,5,opt,name=log_to_console,json=logToConsole,proto3" json:"log_to_console,omitempty"` // 是否输出到控制台
	ExportToOtel  bool                   `protobuf:"varint,6,opt,name=export_to_otel,json=exportToOtel,proto3" json:"export_to_otel,omitempty"` //日志是否导出到OTEL
	MaxSize       int32                  `protobuf:"varint,7,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`                  // 单个日志文件最大大小（MB）
	MaxAge        int32                  `protobuf:"varint,8,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`                     // 日志文件最大保存时间（天）
	MaxBackups    int32                  `protobuf:"varint,9,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"`         // 最大备份文件数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logger_Zap) Reset() {
	*x = Logger_Zap{}
	mi := &file_v1_logger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logger_Zap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logger_Zap) ProtoMessage() {}

func (x *Logger_Zap) ProtoReflect() protoreflect.Message {
	mi := &file_v1_logger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logger_Zap.ProtoReflect.Descriptor instead.
func (*Logger_Zap) Descriptor() ([]byte, []int) {
	return file_v1_logger_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Logger_Zap) GetLogFilePath() string {
	if x != nil {
		return x.LogFilePath
	}
	return ""
}

func (x *Logger_Zap) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Logger_Zap) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

func (x *Logger_Zap) GetLogToConsole() bool {
	if x != nil {
		return x.LogToConsole
	}
	return false
}

func (x *Logger_Zap) GetExportToOtel() bool {
	if x != nil {
		return x.ExportToOtel
	}
	return false
}

func (x *Logger_Zap) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *Logger_Zap) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *Logger_Zap) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

// logrus
type Logger_Logrus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Level            string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`                                                // 日志等级
	Formatter        string                 `protobuf:"bytes,2,opt,name=formatter,proto3" json:"formatter,omitempty"`                                        // 输出格式：text, json.
	TimestampFormat  string                 `protobuf:"bytes,3,opt,name=timestamp_format,json=timestampFormat,proto3" json:"timestamp_format,omitempty"`     // 定义时间戳格式，例如："2006-01-02 15:04:05"
	DisableColors    bool                   `protobuf:"varint,4,opt,name=disable_colors,json=disableColors,proto3" json:"disable_colors,omitempty"`          // 不需要彩色日志
	DisableTimestamp bool                   `protobuf:"varint,5,opt,name=disable_timestamp,json=disableTimestamp,proto3" json:"disable_timestamp,omitempty"` // 不需要时间戳
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Logger_Logrus) Reset() {
	*x = Logger_Logrus{}
	mi := &file_v1_logger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logger_Logrus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logger_Logrus) ProtoMessage() {}

func (x *Logger_Logrus) ProtoReflect() protoreflect.Message {
	mi := &file_v1_logger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logger_Logrus.ProtoReflect.Descriptor instead.
func (*Logger_Logrus) Descriptor() ([]byte, []int) {
	return file_v1_logger_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Logger_Logrus) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Logger_Logrus) GetFormatter() string {
	if x != nil {
		return x.Formatter
	}
	return ""
}

func (x *Logger_Logrus) GetTimestampFormat() string {
	if x != nil {
		return x.TimestampFormat
	}
	return ""
}

func (x *Logger_Logrus) GetDisableColors() bool {
	if x != nil {
		return x.DisableColors
	}
	return false
}

func (x *Logger_Logrus) GetDisableTimestamp() bool {
	if x != nil {
		return x.DisableTimestamp
	}
	return false
}

// Flentd
type Logger_Flentd struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Endpoint           string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                       // 公网接入地址
	Level              string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`                             //日志级别
	Timeout            *durationpb.Duration   `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`                         //超时时间
	WriteTimeout       *durationpb.Duration   `protobuf:"bytes,5,opt,name=writeTimeout,proto3" json:"writeTimeout,omitempty"`               //写超时时间
	BufferLimit        int32                  `protobuf:"varint,6,opt,name=bufferLimit,proto3" json:"bufferLimit,omitempty"`                //缓冲区限制
	RetryWait          int32                  `protobuf:"varint,7,opt,name=retryWait,proto3" json:"retryWait,omitempty"`                    //重试等待时间
	MaxRetry           int32                  `protobuf:"varint,8,opt,name=maxRetry,proto3" json:"maxRetry,omitempty"`                      //最大重试次数
	MaxRetryWait       int32                  `protobuf:"varint,9,opt,name=maxRetryWait,proto3" json:"maxRetryWait,omitempty"`              //最大重试等待时间
	TagPrefix          string                 `protobuf:"bytes,10,opt,name=tagPrefix,proto3" json:"tagPrefix,omitempty"`                    //标签前缀
	Async              bool                   `protobuf:"varint,11,opt,name=async,proto3" json:"async,omitempty"`                           //是否异步发送
	ForceStopAsyncSend bool                   `protobuf:"varint,12,opt,name=forceStopAsyncSend,proto3" json:"forceStopAsyncSend,omitempty"` //是否强制停止异步发送
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Logger_Flentd) Reset() {
	*x = Logger_Flentd{}
	mi := &file_v1_logger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logger_Flentd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logger_Flentd) ProtoMessage() {}

func (x *Logger_Flentd) ProtoReflect() protoreflect.Message {
	mi := &file_v1_logger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logger_Flentd.ProtoReflect.Descriptor instead.
func (*Logger_Flentd) Descriptor() ([]byte, []int) {
	return file_v1_logger_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Logger_Flentd) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Logger_Flentd) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Logger_Flentd) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Logger_Flentd) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Logger_Flentd) GetBufferLimit() int32 {
	if x != nil {
		return x.BufferLimit
	}
	return 0
}

func (x *Logger_Flentd) GetRetryWait() int32 {
	if x != nil {
		return x.RetryWait
	}
	return 0
}

func (x *Logger_Flentd) GetMaxRetry() int32 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

func (x *Logger_Flentd) GetMaxRetryWait() int32 {
	if x != nil {
		return x.MaxRetryWait
	}
	return 0
}

func (x *Logger_Flentd) GetTagPrefix() string {
	if x != nil {
		return x.TagPrefix
	}
	return ""
}

func (x *Logger_Flentd) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

func (x *Logger_Flentd) GetForceStopAsyncSend() bool {
	if x != nil {
		return x.ForceStopAsyncSend
	}
	return false
}

// 阿里云
type Logger_Aliyun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                             // 公网接入地址
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`                               // 项目ID
	AccessKey     string                 `protobuf:"bytes,3,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`          // 访问密钥ID
	AccessSecret  string                 `protobuf:"bytes,4,opt,name=access_secret,json=accessSecret,proto3" json:"access_secret,omitempty"` // 访问密钥
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logger_Aliyun) Reset() {
	*x = Logger_Aliyun{}
	mi := &file_v1_logger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logger_Aliyun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logger_Aliyun) ProtoMessage() {}

func (x *Logger_Aliyun) ProtoReflect() protoreflect.Message {
	mi := &file_v1_logger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logger_Aliyun.ProtoReflect.Descriptor instead.
func (*Logger_Aliyun) Descriptor() ([]byte, []int) {
	return file_v1_logger_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Logger_Aliyun) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Logger_Aliyun) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *Logger_Aliyun) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *Logger_Aliyun) GetAccessSecret() string {
	if x != nil {
		return x.AccessSecret
	}
	return ""
}

// 腾讯
type Logger_Tencent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                             // 公网接入地址
	TopicId       string                 `protobuf:"bytes,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`                // 主题ID
	AccessKey     string                 `protobuf:"bytes,3,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`          // 访问密钥ID
	AccessSecret  string                 `protobuf:"bytes,4,opt,name=access_secret,json=accessSecret,proto3" json:"access_secret,omitempty"` // 访问密钥
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logger_Tencent) Reset() {
	*x = Logger_Tencent{}
	mi := &file_v1_logger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logger_Tencent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logger_Tencent) ProtoMessage() {}

func (x *Logger_Tencent) ProtoReflect() protoreflect.Message {
	mi := &file_v1_logger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logger_Tencent.ProtoReflect.Descriptor instead.
func (*Logger_Tencent) Descriptor() ([]byte, []int) {
	return file_v1_logger_proto_rawDescGZIP(), []int{0, 4}
}

func (x *Logger_Tencent) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Logger_Tencent) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *Logger_Tencent) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *Logger_Tencent) GetAccessSecret() string {
	if x != nil {
		return x.AccessSecret
	}
	return ""
}

// Zerolog
type Logger_Zerolog struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Level              string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`                                                       // 日志等级
	TimeFieldFormat    string                 `protobuf:"bytes,2,opt,name=time_field_format,json=timeFieldFormat,proto3" json:"time_field_format,omitempty"`          // 定义时间戳格式，例如："2006-01-02 15:04:05"
	TimestampFieldName string                 `protobuf:"bytes,3,opt,name=timestamp_field_name,json=timestampFieldName,proto3" json:"timestamp_field_name,omitempty"` // 时间戳字段名称
	LevelFieldName     string                 `protobuf:"bytes,4,opt,name=level_field_name,json=levelFieldName,proto3" json:"level_field_name,omitempty"`             // 日志等级字段名称
	MessageFieldName   string                 `protobuf:"bytes,5,opt,name=message_field_name,json=messageFieldName,proto3" json:"message_field_name,omitempty"`       // 日志消息字段名称
	Writer             string                 `protobuf:"bytes,6,opt,name=writer,proto3" json:"writer,omitempty"`                                                     // 输出目标，默认stdout，可选：stdout, stderr, file
	Filename           string                 `protobuf:"bytes,7,opt,name=filename,proto3" json:"filename,omitempty"`                                                 // 当writer为file时，指定日志文件名
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Logger_Zerolog) Reset() {
	*x = Logger_Zerolog{}
	mi := &file_v1_logger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logger_Zerolog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logger_Zerolog) ProtoMessage() {}

func (x *Logger_Zerolog) ProtoReflect() protoreflect.Message {
	mi := &file_v1_logger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logger_Zerolog.ProtoReflect.Descriptor instead.
func (*Logger_Zerolog) Descriptor() ([]byte, []int) {
	return file_v1_logger_proto_rawDescGZIP(), []int{0, 5}
}

func (x *Logger_Zerolog) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Logger_Zerolog) GetTimeFieldFormat() string {
	if x != nil {
		return x.TimeFieldFormat
	}
	return ""
}

func (x *Logger_Zerolog) GetTimestampFieldName() string {
	if x != nil {
		return x.TimestampFieldName
	}
	return ""
}

func (x *Logger_Zerolog) GetLevelFieldName() string {
	if x != nil {
		return x.LevelFieldName
	}
	return ""
}

func (x *Logger_Zerolog) GetMessageFieldName() string {
	if x != nil {
		return x.MessageFieldName
	}
	return ""
}

func (x *Logger_Zerolog) GetWriter() string {
	if x != nil {
		return x.Writer
	}
	return ""
}

func (x *Logger_Zerolog) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_v1_logger_proto protoreflect.FileDescriptor

const file_v1_logger_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/logger.proto\x12\x04conf\x1a\x1egoogle/protobuf/duration.proto\"\xcc\x0e\n" +
	"\x06Logger\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12'\n" +
	"\x03zap\x18\x02 \x01(\v2\x10.conf.Logger.ZapH\x00R\x03zap\x88\x01\x01\x120\n" +
	"\x06logrus\x18\x03 \x01(\v2\x13.conf.Logger.LogrusH\x01R\x06logrus\x88\x01\x01\x122\n" +
	"\afluentd\x18\x04 \x01(\v2\x13.conf.Logger.FlentdH\x02R\afluentd\x88\x01\x01\x120\n" +
	"\x06aliyun\x18\x05 \x01(\v2\x13.conf.Logger.AliyunH\x03R\x06aliyun\x88\x01\x01\x123\n" +
	"\atencent\x18\x06 \x01(\v2\x14.conf.Logger.TencentH\x04R\atencent\x88\x01\x01\x123\n" +
	"\azerolog\x18\a \x01(\v2\x14.conf.Logger.ZerologH\x05R\azerolog\x88\x01\x01\x1a\xf8\x01\n" +
	"\x03Zap\x12\"\n" +
	"\rlog_file_path\x18\x01 \x01(\tR\vlogFilePath\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x16\n" +
	"\x06caller\x18\x03 \x01(\tR\x06caller\x12$\n" +
	"\x0elog_to_console\x18\x05 \x01(\bR\flogToConsole\x12$\n" +
	"\x0eexport_to_otel\x18\x06 \x01(\bR\fexportToOtel\x12\x19\n" +
	"\bmax_size\x18\a \x01(\x05R\amaxSize\x12\x17\n" +
	"\amax_age\x18\b \x01(\x05R\x06maxAge\x12\x1f\n" +
	"\vmax_backups\x18\t \x01(\x05R\n" +
	"maxBackups\x1a\xbb\x01\n" +
	"\x06Logrus\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x1c\n" +
	"\tformatter\x18\x02 \x01(\tR\tformatter\x12)\n" +
	"\x10timestamp_format\x18\x03 \x01(\tR\x0ftimestampFormat\x12%\n" +
	"\x0edisable_colors\x18\x04 \x01(\bR\rdisableColors\x12+\n" +
	"\x11disable_timestamp\x18\x05 \x01(\bR\x10disableTimestamp\x1a\x92\x03\n" +
	"\x06Flentd\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x123\n" +
	"\atimeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12=\n" +
	"\fwriteTimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12 \n" +
	"\vbufferLimit\x18\x06 \x01(\x05R\vbufferLimit\x12\x1c\n" +
	"\tretryWait\x18\a \x01(\x05R\tretryWait\x12\x1a\n" +
	"\bmaxRetry\x18\b \x01(\x05R\bmaxRetry\x12\"\n" +
	"\fmaxRetryWait\x18\t \x01(\x05R\fmaxRetryWait\x12\x1c\n" +
	"\ttagPrefix\x18\n" +
	" \x01(\tR\ttagPrefix\x12\x14\n" +
	"\x05async\x18\v \x01(\bR\x05async\x12.\n" +
	"\x12forceStopAsyncSend\x18\f \x01(\bR\x12forceStopAsyncSend\x1a\x82\x01\n" +
	"\x06Aliyun\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x1d\n" +
	"\n" +
	"access_key\x18\x03 \x01(\tR\taccessKey\x12#\n" +
	"\raccess_secret\x18\x04 \x01(\tR\faccessSecret\x1a\x84\x01\n" +
	"\aTencent\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\tR\atopicId\x12\x1d\n" +
	"\n" +
	"access_key\x18\x03 \x01(\tR\taccessKey\x12#\n" +
	"\raccess_secret\x18\x04 \x01(\tR\faccessSecret\x1a\x89\x02\n" +
	"\aZerolog\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12*\n" +
	"\x11time_field_format\x18\x02 \x01(\tR\x0ftimeFieldFormat\x120\n" +
	"\x14timestamp_field_name\x18\x03 \x01(\tR\x12timestampFieldName\x12(\n" +
	"\x10level_field_name\x18\x04 \x01(\tR\x0elevelFieldName\x12,\n" +
	"\x12message_field_name\x18\x05 \x01(\tR\x10messageFieldName\x12\x16\n" +
	"\x06writer\x18\x06 \x01(\tR\x06writer\x12\x1a\n" +
	"\bfilename\x18\a \x01(\tR\bfilename\"[\n" +
	"\x04Type\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03ZAP\x10\x01\x12\n" +
	"\n" +
	"\x06LOGRUS\x10\x02\x12\v\n" +
	"\aFLUENTD\x10\x03\x12\n" +
	"\n" +
	"\x06ALIYUN\x10\x04\x12\v\n" +
	"\aTENCENT\x10\x05\x12\v\n" +
	"\aZEROLOG\x10\x06B\x06\n" +
	"\x04_zapB\t\n" +
	"\a_logrusB\n" +
	"\n" +
	"\b_fluentdB\t\n" +
	"\a_aliyunB\n" +
	"\n" +
	"\b_tencentB\n" +
	"\n" +
	"\b_zerologB'Z%github.com/chnxq/xkitpkg/conf/v1;confb\x06proto3"

var (
	file_v1_logger_proto_rawDescOnce sync.Once
	file_v1_logger_proto_rawDescData []byte
)

func file_v1_logger_proto_rawDescGZIP() []byte {
	file_v1_logger_proto_rawDescOnce.Do(func() {
		file_v1_logger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_logger_proto_rawDesc), len(file_v1_logger_proto_rawDesc)))
	})
	return file_v1_logger_proto_rawDescData
}

var file_v1_logger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_logger_proto_goTypes = []any{
	(Logger_Type)(0),            // 0: conf.Logger.Type
	(*Logger)(nil),              // 1: conf.Logger
	(*Logger_Zap)(nil),          // 2: conf.Logger.Zap
	(*Logger_Logrus)(nil),       // 3: conf.Logger.Logrus
	(*Logger_Flentd)(nil),       // 4: conf.Logger.Flentd
	(*Logger_Aliyun)(nil),       // 5: conf.Logger.Aliyun
	(*Logger_Tencent)(nil),      // 6: conf.Logger.Tencent
	(*Logger_Zerolog)(nil),      // 7: conf.Logger.Zerolog
	(*durationpb.Duration)(nil), // 8: google.protobuf.Duration
}
var file_v1_logger_proto_depIdxs = []int32{
	2, // 0: conf.Logger.zap:type_name -> conf.Logger.Zap
	3, // 1: conf.Logger.logrus:type_name -> conf.Logger.Logrus
	4, // 2: conf.Logger.fluentd:type_name -> conf.Logger.Flentd
	5, // 3: conf.Logger.aliyun:type_name -> conf.Logger.Aliyun
	6, // 4: conf.Logger.tencent:type_name -> conf.Logger.Tencent
	7, // 5: conf.Logger.zerolog:type_name -> conf.Logger.Zerolog
	8, // 6: conf.Logger.Flentd.timeout:type_name -> google.protobuf.Duration
	8, // 7: conf.Logger.Flentd.writeTimeout:type_name -> google.protobuf.Duration
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_v1_logger_proto_init() }
func file_v1_logger_proto_init() {
	if File_v1_logger_proto != nil {
		return
	}
	file_v1_logger_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_logger_proto_rawDesc), len(file_v1_logger_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_logger_proto_goTypes,
		DependencyIndexes: file_v1_logger_proto_depIdxs,
		EnumInfos:         file_v1_logger_proto_enumTypes,
		MessageInfos:      file_v1_logger_proto_msgTypes,
	}.Build()
	File_v1_logger_proto = out.File
	file_v1_logger_proto_goTypes = nil
	file_v1_logger_proto_depIdxs = nil
}
