// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/proxy.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务代理
type Proxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsUrl         bool                   `protobuf:"varint,1,opt,name=isUrl,proto3" json:"isUrl,omitempty"`  // url：true，本地路径静态资源，false
	Prefix        string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"` // 前缀
	Addr          string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`     // 转发地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proxy) Reset() {
	*x = Proxy{}
	mi := &file_v1_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proxy) ProtoMessage() {}

func (x *Proxy) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proxy.ProtoReflect.Descriptor instead.
func (*Proxy) Descriptor() ([]byte, []int) {
	return file_v1_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *Proxy) GetIsUrl() bool {
	if x != nil {
		return x.IsUrl
	}
	return false
}

func (x *Proxy) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Proxy) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

var File_v1_proxy_proto protoreflect.FileDescriptor

const file_v1_proxy_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/proxy.proto\x12\x04conf\"I\n" +
	"\x05Proxy\x12\x14\n" +
	"\x05isUrl\x18\x01 \x01(\bR\x05isUrl\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addrB'Z%github.com/chnxq/xkitpkg/conf/v1;confb\x06proto3"

var (
	file_v1_proxy_proto_rawDescOnce sync.Once
	file_v1_proxy_proto_rawDescData []byte
)

func file_v1_proxy_proto_rawDescGZIP() []byte {
	file_v1_proxy_proto_rawDescOnce.Do(func() {
		file_v1_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_proxy_proto_rawDesc), len(file_v1_proxy_proto_rawDesc)))
	})
	return file_v1_proxy_proto_rawDescData
}

var file_v1_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_proxy_proto_goTypes = []any{
	(*Proxy)(nil), // 0: conf.Proxy
}
var file_v1_proxy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_proxy_proto_init() }
func file_v1_proxy_proto_init() {
	if File_v1_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_proxy_proto_rawDesc), len(file_v1_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_proxy_proto_goTypes,
		DependencyIndexes: file_v1_proxy_proto_depIdxs,
		MessageInfos:      file_v1_proxy_proto_msgTypes,
	}.Build()
	File_v1_proxy_proto = out.File
	file_v1_proxy_proto_goTypes = nil
	file_v1_proxy_proto_depIdxs = nil
}
