// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/server_config.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务整体配置信息
type ServerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3,oneof" json:"server,omitempty"`     // 服务器配置
	Client        *Client                `protobuf:"bytes,2,opt,name=client,proto3,oneof" json:"client,omitempty"`     // 客户端配置
	Data          *Data                  `protobuf:"bytes,3,opt,name=data,proto3,oneof" json:"data,omitempty"`         // 数据存储配置(数据库、缓存)
	Trace         *Tracer                `protobuf:"bytes,4,opt,name=trace,proto3,oneof" json:"trace,omitempty"`       // 链路追踪配置
	Logger        *Logger                `protobuf:"bytes,5,opt,name=logger,proto3,oneof" json:"logger,omitempty"`     // 日志配置
	Registry      *Registry              `protobuf:"bytes,6,opt,name=registry,proto3,oneof" json:"registry,omitempty"` // 注册发现中心配置
	Config        *RemoteConfig          `protobuf:"bytes,7,opt,name=config,proto3,oneof" json:"config,omitempty"`     // 远程配置服务
	Oss           *OSS                   `protobuf:"bytes,8,opt,name=oss,proto3,oneof" json:"oss,omitempty"`           // 对象存储配置
	Notify        *Notification          `protobuf:"bytes,9,opt,name=notify,proto3,oneof" json:"notify,omitempty"`     // 通知消息配置
	Authn         *Authentication        `protobuf:"bytes,10,opt,name=authn,proto3,oneof" json:"authn,omitempty"`      // 认证配置
	Authz         *Authorization         `protobuf:"bytes,11,opt,name=authz,proto3,oneof" json:"authz,omitempty"`      // 授权配置
	Script        *Script                `protobuf:"bytes,12,opt,name=script,proto3,oneof" json:"script,omitempty"`    // 脚本引擎配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_v1_server_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_server_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_v1_server_config_proto_rawDescGZIP(), []int{0}
}

func (x *ServerConfig) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ServerConfig) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *ServerConfig) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ServerConfig) GetTrace() *Tracer {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *ServerConfig) GetLogger() *Logger {
	if x != nil {
		return x.Logger
	}
	return nil
}

func (x *ServerConfig) GetRegistry() *Registry {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *ServerConfig) GetConfig() *RemoteConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ServerConfig) GetOss() *OSS {
	if x != nil {
		return x.Oss
	}
	return nil
}

func (x *ServerConfig) GetNotify() *Notification {
	if x != nil {
		return x.Notify
	}
	return nil
}

func (x *ServerConfig) GetAuthn() *Authentication {
	if x != nil {
		return x.Authn
	}
	return nil
}

func (x *ServerConfig) GetAuthz() *Authorization {
	if x != nil {
		return x.Authz
	}
	return nil
}

func (x *ServerConfig) GetScript() *Script {
	if x != nil {
		return x.Script
	}
	return nil
}

var File_v1_server_config_proto protoreflect.FileDescriptor

const file_v1_server_config_proto_rawDesc = "" +
	"\n" +
	"\x16v1/server_config.proto\x12\x04conf\x1a\x0fv1/tracer.proto\x1a\rv1/data.proto\x1a\x0fv1/server.proto\x1a\x0fv1/client.proto\x1a\x0fv1/logger.proto\x1a\x11v1/registry.proto\x1a\fv1/oss.proto\x1a\x0fv1/config.proto\x1a\x0fv1/notify.proto\x1a\x0ev1/authn.proto\x1a\x0ev1/authz.proto\x1a\x0fv1/script.proto\"\x9c\x05\n" +
	"\fServerConfig\x12)\n" +
	"\x06server\x18\x01 \x01(\v2\f.conf.ServerH\x00R\x06server\x88\x01\x01\x12)\n" +
	"\x06client\x18\x02 \x01(\v2\f.conf.ClientH\x01R\x06client\x88\x01\x01\x12#\n" +
	"\x04data\x18\x03 \x01(\v2\n" +
	".conf.DataH\x02R\x04data\x88\x01\x01\x12'\n" +
	"\x05trace\x18\x04 \x01(\v2\f.conf.TracerH\x03R\x05trace\x88\x01\x01\x12)\n" +
	"\x06logger\x18\x05 \x01(\v2\f.conf.LoggerH\x04R\x06logger\x88\x01\x01\x12/\n" +
	"\bregistry\x18\x06 \x01(\v2\x0e.conf.RegistryH\x05R\bregistry\x88\x01\x01\x12/\n" +
	"\x06config\x18\a \x01(\v2\x12.conf.RemoteConfigH\x06R\x06config\x88\x01\x01\x12 \n" +
	"\x03oss\x18\b \x01(\v2\t.conf.OSSH\aR\x03oss\x88\x01\x01\x12/\n" +
	"\x06notify\x18\t \x01(\v2\x12.conf.NotificationH\bR\x06notify\x88\x01\x01\x12/\n" +
	"\x05authn\x18\n" +
	" \x01(\v2\x14.conf.AuthenticationH\tR\x05authn\x88\x01\x01\x12.\n" +
	"\x05authz\x18\v \x01(\v2\x13.conf.AuthorizationH\n" +
	"R\x05authz\x88\x01\x01\x12)\n" +
	"\x06script\x18\f \x01(\v2\f.conf.ScriptH\vR\x06script\x88\x01\x01B\t\n" +
	"\a_serverB\t\n" +
	"\a_clientB\a\n" +
	"\x05_dataB\b\n" +
	"\x06_traceB\t\n" +
	"\a_loggerB\v\n" +
	"\t_registryB\t\n" +
	"\a_configB\x06\n" +
	"\x04_ossB\t\n" +
	"\a_notifyB\b\n" +
	"\x06_authnB\b\n" +
	"\x06_authzB\t\n" +
	"\a_scriptB'Z%github.com/chnxq/xkitpkg/conf/v1;confb\x06proto3"

var (
	file_v1_server_config_proto_rawDescOnce sync.Once
	file_v1_server_config_proto_rawDescData []byte
)

func file_v1_server_config_proto_rawDescGZIP() []byte {
	file_v1_server_config_proto_rawDescOnce.Do(func() {
		file_v1_server_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_server_config_proto_rawDesc), len(file_v1_server_config_proto_rawDesc)))
	})
	return file_v1_server_config_proto_rawDescData
}

var file_v1_server_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_server_config_proto_goTypes = []any{
	(*ServerConfig)(nil),   // 0: conf.ServerConfig
	(*Server)(nil),         // 1: conf.Server
	(*Client)(nil),         // 2: conf.Client
	(*Data)(nil),           // 3: conf.Data
	(*Tracer)(nil),         // 4: conf.Tracer
	(*Logger)(nil),         // 5: conf.Logger
	(*Registry)(nil),       // 6: conf.Registry
	(*RemoteConfig)(nil),   // 7: conf.RemoteConfig
	(*OSS)(nil),            // 8: conf.OSS
	(*Notification)(nil),   // 9: conf.Notification
	(*Authentication)(nil), // 10: conf.Authentication
	(*Authorization)(nil),  // 11: conf.Authorization
	(*Script)(nil),         // 12: conf.Script
}
var file_v1_server_config_proto_depIdxs = []int32{
	1,  // 0: conf.ServerConfig.server:type_name -> conf.Server
	2,  // 1: conf.ServerConfig.client:type_name -> conf.Client
	3,  // 2: conf.ServerConfig.data:type_name -> conf.Data
	4,  // 3: conf.ServerConfig.trace:type_name -> conf.Tracer
	5,  // 4: conf.ServerConfig.logger:type_name -> conf.Logger
	6,  // 5: conf.ServerConfig.registry:type_name -> conf.Registry
	7,  // 6: conf.ServerConfig.config:type_name -> conf.RemoteConfig
	8,  // 7: conf.ServerConfig.oss:type_name -> conf.OSS
	9,  // 8: conf.ServerConfig.notify:type_name -> conf.Notification
	10, // 9: conf.ServerConfig.authn:type_name -> conf.Authentication
	11, // 10: conf.ServerConfig.authz:type_name -> conf.Authorization
	12, // 11: conf.ServerConfig.script:type_name -> conf.Script
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_server_config_proto_init() }
func file_v1_server_config_proto_init() {
	if File_v1_server_config_proto != nil {
		return
	}
	file_v1_tracer_proto_init()
	file_v1_data_proto_init()
	file_v1_server_proto_init()
	file_v1_client_proto_init()
	file_v1_logger_proto_init()
	file_v1_registry_proto_init()
	file_v1_oss_proto_init()
	file_v1_config_proto_init()
	file_v1_notify_proto_init()
	file_v1_authn_proto_init()
	file_v1_authz_proto_init()
	file_v1_script_proto_init()
	file_v1_server_config_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_server_config_proto_rawDesc), len(file_v1_server_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_server_config_proto_goTypes,
		DependencyIndexes: file_v1_server_config_proto_depIdxs,
		MessageInfos:      file_v1_server_config_proto_msgTypes,
	}.Build()
	File_v1_server_config_proto = out.File
	file_v1_server_config_proto_goTypes = nil
	file_v1_server_config_proto_depIdxs = nil
}
